language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t bryansmullen/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bryansmullen/docker-react npm run test